export default {
  register() { },
  async bootstrap({ strapi }) {
    // Seed transfer routes if none exist
    try {
      const transferCount = await strapi.db.query('api::transfer-route.transfer-route').count();
      if (transferCount === 0) {
        const transferRoutes = [
          {
            name: "Zanzibar Airport to Nungwi Beach",
            slug: "zanzibar-airport-to-nungwi",
            description: "Enjoy a comfortable and scenic drive from Zanzibar Airport to the stunning Nungwi Beach on the northern tip of the island. Our professional drivers will ensure you arrive relaxed and ready to enjoy paradise. The route passes through local villages and spice plantations, giving you a first taste of Zanzibar's culture.",
            pickupLocation: "Zanzibar Airport (ZNZ)",
            dropoffLocation: "Nungwi Beach",
            distance: "58 km",
            duration: "1h 15min",
            price: 45,
            priceReturn: 80,
            vehicleType: "Sedan / Minivan",
            featured: true,
            order: 1,
            publishedAt: new Date(),
          },
          {
            name: "Zanzibar Airport to Stone Town",
            slug: "zanzibar-airport-to-stone-town",
            description: "Quick and convenient transfer from Zanzibar Airport to the historic Stone Town, a UNESCO World Heritage Site. Our drivers know the narrow streets well and will drop you as close to your hotel as possible.",
            pickupLocation: "Zanzibar Airport (ZNZ)",
            dropoffLocation: "Stone Town",
            distance: "8 km",
            duration: "20min",
            price: 20,
            priceReturn: 35,
            vehicleType: "Sedan",
            featured: true,
            order: 2,
            publishedAt: new Date(),
          },
          {
            name: "Zanzibar Airport to Paje Beach",
            slug: "zanzibar-airport-to-paje",
            description: "Relax as we drive you from Zanzibar Airport to the beautiful Paje Beach on the east coast. Known for its kitesurfing and powdery white sand, Paje is a favorite among adventurous travelers.",
            pickupLocation: "Zanzibar Airport (ZNZ)",
            dropoffLocation: "Paje Beach",
            distance: "42 km",
            duration: "55min",
            price: 40,
            priceReturn: 70,
            vehicleType: "Sedan / Minivan",
            featured: false,
            order: 3,
            publishedAt: new Date(),
          },
          {
            name: "Zanzibar Airport to Kendwa Beach",
            slug: "zanzibar-airport-to-kendwa",
            description: "Smooth transfer from the airport to the popular Kendwa Beach resort area. Kendwa is known for its stunning sunsets and vibrant beach parties.",
            pickupLocation: "Zanzibar Airport (ZNZ)",
            dropoffLocation: "Kendwa Beach",
            distance: "55 km",
            duration: "1h 10min",
            price: 45,
            priceReturn: 80,
            vehicleType: "Sedan / Minivan",
            featured: false,
            order: 4,
            publishedAt: new Date(),
          },
          {
            name: "Dar Airport to Masaki",
            slug: "dar-airport-to-masaki",
            description: "Professional transfer from Julius Nyerere International Airport to the upscale Masaki area in Dar es Salaam. Masaki is home to many international restaurants, embassies, and premium hotels.",
            pickupLocation: "Julius Nyerere Airport (DAR)",
            dropoffLocation: "Masaki, Dar es Salaam",
            distance: "15 km",
            duration: "30min",
            price: 35,
            priceReturn: 60,
            vehicleType: "Sedan / SUV",
            featured: true,
            order: 5,
            publishedAt: new Date(),
          },
          {
            name: "Dar Airport to City Center",
            slug: "dar-airport-to-city-center",
            description: "Reliable transfer from Julius Nyerere International Airport to the Dar es Salaam city center. Avoid the hassle of negotiating with taxi drivers and arrive in comfort.",
            pickupLocation: "Julius Nyerere Airport (DAR)",
            dropoffLocation: "Dar es Salaam City Center",
            distance: "12 km",
            duration: "25min",
            price: 30,
            priceReturn: 50,
            vehicleType: "Sedan",
            featured: false,
            order: 6,
            publishedAt: new Date(),
          },
          {
            name: "Stone Town to Paje Beach",
            slug: "stone-town-to-paje",
            description: "Travel from Stone Town to the east coast beaches. Paje offers incredible kitesurfing, snorkeling, and white sand beaches. The drive takes you through the heart of the island.",
            pickupLocation: "Stone Town",
            dropoffLocation: "Paje Beach",
            distance: "35 km",
            duration: "50min",
            price: 35,
            priceReturn: 60,
            vehicleType: "Sedan / Minivan",
            featured: false,
            order: 7,
            publishedAt: new Date(),
          },
          {
            name: "Stone Town to Nungwi Beach",
            slug: "stone-town-to-nungwi",
            description: "Head north from Stone Town to the famous Nungwi Beach. The journey passes through spice farms and traditional villages, offering a glimpse of local island life.",
            pickupLocation: "Stone Town",
            dropoffLocation: "Nungwi Beach",
            distance: "50 km",
            duration: "1h 05min",
            price: 40,
            priceReturn: 70,
            vehicleType: "Sedan / Minivan",
            featured: false,
            order: 8,
            publishedAt: new Date(),
          },
        ];

        for (const route of transferRoutes) {
          await strapi.db.query('api::transfer-route.transfer-route').create({ data: route });
        }
        strapi.log.info(`[Seed] Created ${transferRoutes.length} transfer routes`);
      }
    } catch (e) {
      strapi.log.warn('[Seed] Could not seed transfer routes:', e.message);
    }

    // Seed rental vehicles if none exist
    try {
      const vehicleCount = await strapi.db.query('api::rental-vehicle.rental-vehicle').count();
      if (vehicleCount === 0) {
        const vehicles = [
          {
            name: "Toyota Vitz",
            slug: "toyota-vitz",
            description: "The Toyota Vitz is a perfect city companion — compact, fuel-efficient, and easy to park. Ideal for short trips around Stone Town, Dar es Salaam, or getting to the beach without the fuss. Comes with air conditioning and Bluetooth connectivity.",
            category: "sedan",
            transmission: "automatic",
            seats: 5,
            pricePerDay: 40,
            pricePerWeek: 250,
            features: "AC, Bluetooth, USB Charging, Fuel Efficient",
            available: true,
            featured: true,
            publishedAt: new Date(),
          },
          {
            name: "Toyota RAV4",
            slug: "toyota-rav4",
            description: "The Toyota RAV4 offers the perfect balance between comfort and capability. With 4WD and generous cargo space, it handles both city roads and unpaved tracks with ease. Great for exploring more rural areas while still enjoying a comfortable ride.",
            category: "suv",
            transmission: "automatic",
            seats: 5,
            pricePerDay: 70,
            pricePerWeek: 450,
            features: "AC, 4WD, GPS, Bluetooth, Roof Rack",
            available: true,
            featured: true,
            publishedAt: new Date(),
          },
          {
            name: "Toyota Land Cruiser",
            slug: "toyota-land-cruiser",
            description: "The legendary Toyota Land Cruiser — the king of African safari vehicles. Built for the toughest terrain, this 4x4 comes equipped with everything you need for a self-drive safari adventure, including a pop-up roof hatch for wildlife viewing.",
            category: "4x4",
            transmission: "automatic",
            seats: 7,
            pricePerDay: 120,
            pricePerWeek: 750,
            features: "AC, 4WD, GPS, Safari Ready, Roof Hatch, Cooler Box",
            available: true,
            featured: true,
            publishedAt: new Date(),
          },
          {
            name: "Toyota Hiace",
            slug: "toyota-hiace",
            description: "Need to move a group? The Toyota Hiace is your answer. With seating for up to 14 passengers and ample luggage space, it's perfect for team travel, airport transfers for large groups, or family road trips across Tanzania.",
            category: "van",
            transmission: "manual",
            seats: 14,
            pricePerDay: 90,
            pricePerWeek: 550,
            features: "AC, Large Luggage Space, USB Charging",
            available: true,
            featured: false,
            publishedAt: new Date(),
          },
          {
            name: "Suzuki Alto",
            slug: "suzuki-alto",
            description: "Budget-friendly and extremely fuel-efficient. The Suzuki Alto is perfect for solo travelers or couples looking to save on transportation costs while maintaining independence.",
            category: "sedan",
            transmission: "manual",
            seats: 4,
            pricePerDay: 30,
            pricePerWeek: 180,
            features: "AC, Fuel Efficient, Compact",
            available: true,
            featured: false,
            publishedAt: new Date(),
          },
          {
            name: "Toyota Fortuner",
            slug: "toyota-fortuner",
            description: "Premium comfort meets rugged capability. The Toyota Fortuner offers leather seating, advanced audio, and 4WD capability in a stylish package. Perfect for those who want to explore in luxury.",
            category: "luxury",
            transmission: "automatic",
            seats: 7,
            pricePerDay: 100,
            pricePerWeek: 650,
            features: "AC, 4WD, Leather Seats, GPS, Bluetooth, Premium Audio",
            available: true,
            featured: false,
            publishedAt: new Date(),
          },
          {
            name: "Nissan March",
            slug: "nissan-march",
            description: "An economical choice for city driving. The Nissan March is nimble, light on fuel, and perfect for navigating Dar es Salaam's busy streets or making quick trips around Zanzibar.",
            category: "sedan",
            transmission: "automatic",
            seats: 5,
            pricePerDay: 35,
            pricePerWeek: 220,
            features: "AC, Bluetooth, Compact, Fuel Efficient",
            available: true,
            featured: false,
            publishedAt: new Date(),
          },
          {
            name: "Toyota Prado",
            slug: "toyota-prado",
            description: "A premium 4x4 SUV that combines luxury with off-road prowess. The Toyota Prado is ideal for extended safari trips, offering spacious interiors, powerful performance, and advanced comfort features.",
            category: "4x4",
            transmission: "automatic",
            seats: 7,
            pricePerDay: 110,
            pricePerWeek: 700,
            features: "AC, 4WD, Leather Seats, GPS, Roof Rack, Cooler Box, USB Charging",
            available: true,
            featured: true,
            publishedAt: new Date(),
          },
        ];

        for (const vehicle of vehicles) {
          await strapi.db.query('api::rental-vehicle.rental-vehicle').create({ data: vehicle });
        }
        strapi.log.info(`[Seed] Created ${vehicles.length} rental vehicles`);
      }
    } catch (e) {
      strapi.log.warn('[Seed] Could not seed rental vehicles:', e.message);
    }
  },
};

